version = 1
name = "expo-uniwind-starter"

[setup]
script = "pnpm install --frozen-lockfile && pnpm run prebuild"

[[actions]]
name = "Run IOS"
icon = "run"
command = "pnpm ios"

[[actions]]
name = "API Server"
icon = "run"
command = "pnpm run server:dev"

[[actions]]
name = "Check"
icon = "tool"
command = "pnpm run check"

[[actions]]
name = "Test"
icon = "test"
command = "pnpm test"

[[actions]]
name = "Typecheck"
icon = "check"
command = "pnpm typecheck"
